use super::blackjack::{Card, FaceValue, Suit};

#[rustfmt::skip]
pub const UNSHUFFLED_DECK: [Card; 52] = [
  Card { suit: Suit::Hearts, face_value: FaceValue::Two, face_down: false, },
  Card { suit: Suit::Hearts, face_value: FaceValue::Three, face_down: false, },
  Card { suit: Suit::Hearts, face_value: FaceValue::Four, face_down: false, },
  Card { suit: Suit::Hearts, face_value: FaceValue::Five, face_down: false, },
  Card { suit: Suit::Hearts, face_value: FaceValue::Six, face_down: false, },
  Card { suit: Suit::Hearts, face_value: FaceValue::Seven, face_down: false, },
  Card { suit: Suit::Hearts, face_value: FaceValue::Eight, face_down: false, },
  Card { suit: Suit::Hearts, face_value: FaceValue::Nine, face_down: false, },
  Card { suit: Suit::Hearts, face_value: FaceValue::Ten, face_down: false, },
  Card { suit: Suit::Hearts, face_value: FaceValue::Jack, face_down: false, },
  Card { suit: Suit::Hearts, face_value: FaceValue::Queen, face_down: false, },
  Card { suit: Suit::Hearts, face_value: FaceValue::King, face_down: false, },
  Card { suit: Suit::Hearts, face_value: FaceValue::Ace, face_down: false, },

  Card { suit: Suit::Diamonds, face_value: FaceValue::Two, face_down: false, },
  Card { suit: Suit::Diamonds, face_value: FaceValue::Three, face_down: false, },
  Card { suit: Suit::Diamonds, face_value: FaceValue::Four, face_down: false, },
  Card { suit: Suit::Diamonds, face_value: FaceValue::Five, face_down: false, },
  Card { suit: Suit::Diamonds, face_value: FaceValue::Six, face_down: false, },
  Card { suit: Suit::Diamonds, face_value: FaceValue::Seven, face_down: false, },
  Card { suit: Suit::Diamonds, face_value: FaceValue::Eight, face_down: false, },
  Card { suit: Suit::Diamonds, face_value: FaceValue::Nine, face_down: false, },
  Card { suit: Suit::Diamonds, face_value: FaceValue::Ten, face_down: false, },
  Card { suit: Suit::Diamonds, face_value: FaceValue::Jack, face_down: false, },
  Card { suit: Suit::Diamonds, face_value: FaceValue::Queen, face_down: false, },
  Card { suit: Suit::Diamonds, face_value: FaceValue::King, face_down: false, },
  Card { suit: Suit::Diamonds, face_value: FaceValue::Ace, face_down: false, },

  Card { suit: Suit::Clubs, face_value: FaceValue::Two, face_down: false, },
  Card { suit: Suit::Clubs, face_value: FaceValue::Three, face_down: false, },
  Card { suit: Suit::Clubs, face_value: FaceValue::Four, face_down: false, },
  Card { suit: Suit::Clubs, face_value: FaceValue::Five, face_down: false, },
  Card { suit: Suit::Clubs, face_value: FaceValue::Six, face_down: false, },
  Card { suit: Suit::Clubs, face_value: FaceValue::Seven, face_down: false, },
  Card { suit: Suit::Clubs, face_value: FaceValue::Eight, face_down: false, },
  Card { suit: Suit::Clubs, face_value: FaceValue::Nine, face_down: false, },
  Card { suit: Suit::Clubs, face_value: FaceValue::Ten, face_down: false, },
  Card { suit: Suit::Clubs, face_value: FaceValue::Jack, face_down: false, },
  Card { suit: Suit::Clubs, face_value: FaceValue::Queen, face_down: false, },
  Card { suit: Suit::Clubs, face_value: FaceValue::King, face_down: false, },
  Card { suit: Suit::Clubs, face_value: FaceValue::Ace, face_down: false, },

  Card { suit: Suit::Spades, face_value: FaceValue::Two, face_down: false, },
  Card { suit: Suit::Spades, face_value: FaceValue::Three, face_down: false, },
  Card { suit: Suit::Spades, face_value: FaceValue::Four, face_down: false, },
  Card { suit: Suit::Spades, face_value: FaceValue::Five, face_down: false, },
  Card { suit: Suit::Spades, face_value: FaceValue::Six, face_down: false, },
  Card { suit: Suit::Spades, face_value: FaceValue::Seven, face_down: false, },
  Card { suit: Suit::Spades, face_value: FaceValue::Eight, face_down: false, },
  Card { suit: Suit::Spades, face_value: FaceValue::Nine, face_down: false, },
  Card { suit: Suit::Spades, face_value: FaceValue::Ten, face_down: false, },
  Card { suit: Suit::Spades, face_value: FaceValue::Jack, face_down: false, },
  Card { suit: Suit::Spades, face_value: FaceValue::Queen, face_down: false, },
  Card { suit: Suit::Spades, face_value: FaceValue::King, face_down: false, },
  Card { suit: Suit::Spades, face_value: FaceValue::Ace, face_down: false, },
];
